### PR TITLE
Safer authentication and content rendering for the Superset XBlock

### PR DESCRIPTION
**Pull request by pomegranited**
### Description

This PR makes a number of changes to make the Superset XBlock "safer" for use in courses.

1. Moves sensitive authentication fields out of the XBlock fields and into into `XBLOCK_SETTINGS`, the django setting where we usually store configuration like this.
2. Clarifies configuration fields to distinguish between Superset's `internal_service_url` (formerly `host`) and the external, public `service_url`.
3. Hides Superset content from users marked as "students" in the course.

### Testing instructions

Code review is best done commit by commit.

To test, follow the updated installation instructions to install this plugin with Tutor, and add it to your course.

1. Add a new unit, and add this XBlock via Advanced > Superset Dashboard, and configure its `dashboard_uuid`.
2. Visit the new unit as a course staff member: should display configured Superset dashboard.
3. Visit the new unit as a course student: should display a message, not the Superset dashboard.
4. Visit the Instructor Dashboard, and ensure the Superset Dashboard renders there as expected.

### Author Notes & Concerns

I've got this rendering in Studio and the LMS, but not the Instructor Dashboard:  the page spins and never returns, but doesn't show any errors in the LMS either. Not sure what I'm doing wrong. 

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [x] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Comment by pomegranited** [comment]
Hi @Ian2012 CC @bmtcril  Here are my suggestions for the Superset XBlock.

As noted, I'm still having trouble with the Instructor Dashboard plugin part, but I haven't been able to get that working with current `main` yet either. But if this is working for you with an updated configuration, that would be good to know.

Let me know what you think?

**Comment by Ian2012** [comment]
@pomegranited it can be either the permissions or the RLSF, or there is no data for the filters to work. You could try a backfill of course data with tutor dev|local do dump_data_to_clickhouse --options "--object course_overviews"

**Comment by Ian2012** [comment]
@pomegranited However, can you make this contribution to the new platform-plugin-aspects repository?

The XBlock itself wasn't imported in the first migration.

**Comment by felipemontoya** [comment]
@Ian2012 are we planning to migrate the Xblock as well? specially before v1? This contribution looks great, but I am afraid if we merge it here it would not have that much impact.

**Comment by Ian2012** [comment]
Yes, it's expected to be migrated, however, I missed it during the first migration.

**Comment by pomegranited** [comment]
Thanks @Ian2012 

> it can be either the permissions or the RLSF, or there is no data for the filters to work. You could try a backfill of course data with tutor dev|local do dump_data_to_clickhouse --options "--object course_overviews"

That didn't help.. course overviews were already synced. It must be something wrong with my filters config.

> However, can you make this contribution to the new platform-plugin-aspects repository?

Sure thing, I'd be happy to. Do you want me to submit a PR for the whole XBlock, or are you going to port the code first? Happy either way, just let me know.

**Comment by Ian2012** [comment]
@pomegranited If you have time, I would appreciate if you could migrate the whole XBlock.

**Comment by pomegranited** [comment]
@Ian2012 I'd be delighted, thank you for building it :) Will ping you with a PR today/tomorrow.

**Pull request closed without merging**
